from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT))

from dialogue_questions import SOCIAL_CREDIT_QUESTION_POOL, question_pool_by_context


def mermaid_id(node_id: str) -> str:
    return "q_" + re.sub(r"[^0-9A-Za-z_]", "_", node_id)


def mermaid_label(text: str, limit: int = 72) -> str:
    text = " ".join(text.replace("\n", " ").split())
    text = text.replace("HEARING AI:", "").strip()
    text = text.replace('"', "#quot;")
    if len(text) > limit:
        text = text[: limit - 1].rstrip() + "..."
    return text


def main() -> None:
    nodes = SOCIAL_CREDIT_QUESTION_POOL
    grouped = question_pool_by_context()
    explicit_edges = [
        (node_id, choice.next_question_id, choice.intent)
        for node_id, node in nodes.items()
        for choice in node.choices
        if choice.next_question_id
    ]
    selector_based = not explicit_edges

    lines: list[str] = [
        "flowchart TD",
        "  %% Auto-generated by make_mermaid_question_graph.py",
        "  %% This scene uses selector-based routing: after each answered question,",
        "  %% EngineStyleScene.select_next_question_id() selects from unasked questions.",
        "",
        '  START(["start: authority_unfair_law"])',
        '  SELECTOR{{"selector: next unasked question"}}',
        '  EXHAUSTED{{"pool exhausted"}}',
        "",
    ]

    for context, question_ids in sorted(grouped.items()):
        lines.append(f"  subgraph ctx_{context}[{context}]")
        for question_id in question_ids:
            node = nodes[question_id]
            shape_open, shape_close = ("([", "])") if not node.choices else ("[", "]")
            lines.append(
                f'    {mermaid_id(question_id)}{shape_open}"{question_id}<br/>{mermaid_label(node.ai_line)}"{shape_close}'
            )
        lines.append("  end")
        lines.append("")

    lines.append(f"  START --> {mermaid_id('authority_unfair_law')}")

    if selector_based:
        for question_id, node in nodes.items():
            if question_id == "final":
                continue
            if node.choices:
                lines.append(f"  {mermaid_id(question_id)} -->|answer chosen| SELECTOR")
        for question_id, node in nodes.items():
            if question_id == "final":
                continue
            if node.choices:
                lines.append(f"  SELECTOR -.->|may select if unasked| {mermaid_id(question_id)}")
        lines.append("  SELECTOR -->|no unasked questions remain| EXHAUSTED")
        lines.append(f"  EXHAUSTED --> {mermaid_id('final')}")
    else:
        for source_id, target_id, intent in explicit_edges:
            lines.append(f"  {mermaid_id(source_id)} -->|{intent}| {mermaid_id(target_id)}")

    output = ROOT / "question_transitions.mmd"
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {output.name}")


if __name__ == "__main__":
    main()
